---
title: "Mini-curso Noções básicas do R"
author: "Sollano R. Braga"
date: "Novembro de 2017"
output:
  html_notebook:
    highlight: tango
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
  pdf_document:
    toc: yes
    toc_depth: '2'
---

## Atividade 1

Calcular o comprimento médio das pétalas da espécie virginica

```{r}
mean(iris[iris$Species=="virginica", "Petal.Length"], na.rm=T)
```

## Atividade 2

2. Criar um Gráfico de dispersão do comprimento da pétala em função do comprimento da sépala, por espécie, com linha de tendência linear

```{r}
library(ggplot2)
base_grafico <- ggplot(iris, aes(x=Petal.Length, y = Sepal.Length)) +  
  theme_bw(base_family = "serif") +
  theme(
    legend.position = "bottom", 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title = element_text(size = 26, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 26, face = "bold"), 
    axis.text = element_text(size = 23), 
    axis.line.x = element_line(color = "black"), 
    axis.line.y = element_line(color = "black"), 
    strip.text.x = element_text(size = 22,face = "bold"), 
    legend.text = element_text(size = 20), 
    legend.title = element_text(size = 22, face="bold") ) 

base_grafico + geom_point()


```


```{r}

base_grafico + geom_point() + geom_smooth(method = "lm")

```

```{r}

base_grafico + geom_point(aes(color=Species)) + geom_smooth(method = "lm")

```


```{r}

base_grafico + geom_point(aes(color=Species)) + geom_smooth(aes(color=Species),method = "lm")

```
